theme: jekyll-theme-minimal

title: Niaz Khan — CS Portfolio
description: Computer Science Capstone (CS-499) ePortfolio
show_downloads: false

# Profile image
logo: /assets/img/headshot.JPG

# Sidebar details
author: Niaz Khan
location: New York City, USA
email: niazkhan0731@gmail.com
linkedin: https://linkedin.com/in/niazkhan
github: https://github.com/niazkhan0731

# Quick highlights
skills: "Python, Java, MongoDB, SQL, Android Studio, Dash"
cloud: "AWS, Azure"
interests: "AI/ML, Full-Stack Development"

# Certifications
certifications: "CompTIA A+, AWS Cloud Practitioner, Google Project Management Professional"

# Graduation
graduation: "Graduating October 2025 — Southern New Hampshire University (BS Computer Science)"
